/**
 * SDK <-> API Enum-Member Parity
 *
 * routes.json pins the route surface and schema-fields.json's `schemas` pins
 * per-model FIELD NAMES. Neither has ever looked inside a union, so the members
 * of every string-literal type in the SDK were unguarded, and they drifted:
 *
 *   - `DisputeStatus` named OPENED and TIER_1_REVIEW, which exist nowhere in the
 *     API. The three query params that take it declare a strict enum, so either
 *     value was a guaranteed 400.
 *   - `SchemaCompatibilityMode` named FULL/BACKWARD/FORWARD/NONE while every
 *     request site declares them lowercase, so all four documented values were
 *     a 400. The same file already spelled them correctly inline, once.
 *   - `SchemaVersionStatus` named DEPRECATED and DELETED, neither of which the
 *     API has, and omitted DISABLED, which it serves.
 *
 * Each was reachable from a typed, documented parameter. Mocks cannot catch
 * this class (they assert what the SDK sends) and neither can the parity
 * snapshots (built from the SDK's own idea of the shape), so it took a live
 * drive to find. This test is the cheap version of that drive.
 *
 * The `enums` block in schema-fields.json is regenerated by hand from the
 * production OpenAPI (`GET /openapi.json`) on an API version bump, exactly like
 * the `schemas` block above it. A union is pinned only when its members match a
 * spec enum EXACTLY; the rest are listed in `enumsUnpinned`, because guessing
 * which spec enum a union means is how a guard starts lying.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface EnumSnapshot {
  enumCount: number;
  enums: Record<string, { values: string[]; specSites: string[] }>;
  enumsUnpinned: string[];
}

const snapshot: EnumSnapshot = JSON.parse(
  readFileSync(resolve(__dirname, 'schema-fields.json'), 'utf8'),
);
const typesSrc = readFileSync(resolve(__dirname, '../types.ts'), 'utf8');

/**
 * Every `export type X = 'a' | 'b' | (string & {});` in types.ts, mapped to its
 * quoted members. The trailing `(string & {})` is the open-union idiom and is
 * deliberately not a member: it keeps a value the API adds later from being a
 * type error, and says nothing about what the API accepts today.
 *
 * Comments are stripped from the WHOLE source before anything else, and that
 * order is load-bearing. `WebhookEventType` groups its members under `//`
 * headings, one of which contains a semicolon, so scanning for the
 * declaration's terminator first ended the union 36 members early. It parsed,
 * it pinned, and it silently checked a fifth of the type.
 */
function parseUnions(source: string): Record<string, string[]> {
  const src = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
  const out: Record<string, string[]> = {};
  for (const match of src.matchAll(/export type (\w+)\s*=/g)) {
    const start = match.index + match[0].length;
    const end = src.indexOf(';', start);
    if (end === -1) continue;
    const body = src.slice(start, end);
    // String literals, `|`, the open-union idiom, whitespace, and nothing else:
    // any residue means this is not a plain union of string literals.
    if (body.replace(/'[^']*'|\(string & \{\}\)|\||\s/g, '')) continue;
    const values = [...body.matchAll(/'([^']*)'/g)].map((m) => m[1]).sort();
    if (values.length) out[match[1]] = values;
  }
  return out;
}

const unions = parseUnions(typesSrc);

describe('enum-member parity', () => {
  it('parses every union, so a parser slip cannot pass this file silently', () => {
    // A union the parser cannot see is neither pinned nor reported, which is
    // how `WebhookEventType` went unchecked. Exact equality, not a lower bound:
    // a count that merely clears the bar hides a union that dropped out.
    expect(Object.keys(unions).sort()).toEqual(
      [...Object.keys(snapshot.enums), ...snapshot.enumsUnpinned].sort(),
    );
  });

  it('parses whole unions, not the part before the first comment', () => {
    // The specific regression: a semicolon inside a `//` heading truncated
    // WebhookEventType to 8 of its 44 members.
    expect(unions.WebhookEventType).toHaveLength(44);
    expect(unions.WebhookEventType).toContain('*');
    expect(unions.WebhookEventType).toContain('record.settled');
  });

  it('pins every union that has an exact spec enum', () => {
    const pinned = Object.keys(snapshot.enums).sort();
    const known = new Set([...pinned, ...snapshot.enumsUnpinned]);
    const unaccounted = Object.keys(unions).filter((n) => !known.has(n));
    expect(
      unaccounted,
      `New string-literal unions are neither pinned nor listed as unpinned:\n${unaccounted.join(
        '\n',
      )}\nRegenerate the enums block in schema-fields.json from the production OpenAPI.`,
    ).toEqual([]);
  });

  for (const [name, { values, specSites }] of Object.entries(snapshot.enums)) {
    it(`${name} matches the API enum`, () => {
      expect(unions[name], `${name} is no longer a string-literal union`).toBeDefined();
      const sdkValues = unions[name];
      const extra = sdkValues.filter((v) => !values.includes(v));
      const missing = values.filter((v) => !sdkValues.includes(v));
      expect(
        { extra, missing },
        `${name} drifted from ${specSites.join(' + ')}\n` +
          `  SDK names values the API does not have (these 400 when sent): ${extra.join(', ') || 'none'}\n` +
          `  API serves values the SDK does not name: ${missing.join(', ') || 'none'}`,
      ).toEqual({ extra: [], missing: [] });
    });
  }

  it('records why each unpinned union has no spec enum to check against', () => {
    // AcceptanceStatus: the spec declares it `type: ["null","string"]`, free-form.
    // RecordType: customer-registered, so the API cannot enumerate it.
    // RevocationReason: no enum on the wire.
    expect(snapshot.enumsUnpinned).toEqual(['AcceptanceStatus', 'RecordType', 'RevocationReason']);
  });
});
